### ISSUE TITLE
Why didn't you use babel transpiler?

### ISSUE THREAD

**Issue by deeperx** [sanex3339/javascript-obfuscator#11]
Hey there. Awesome work indeed. Thank you.

With babel transpiler it's easy to get an AST tree and generate obfuscated code through it. Why didn't you just use it and write it on your own again? I just wonder about your reasonings.

**Comment by sanex3339** [comment]
Because i didn't know about it. Anyway, i'm absolutely happy with `esprima`

**Comment by deeperx** [comment]
Then, why babel didn't use esprima while such a parser exists :) I'm going to ask them.

Inanc Gumus

16 Ağu 2016 tarihinde 08:27 saatinde, Timofey Kachalov <notifications@github.com> şunları yazdı:

> esprima
