### ISSUE TITLE
Source maps

### ISSUE THREAD

**Issue by nickdima** [sanex3339/javascript-obfuscator#7]
Are source maps possible to implement?

**Comment by sanex3339** [comment]
I haven't see no point to even looking into source maps direction, because main goal of obfuscated code is to hide source code.

**Comment by nickdima** [comment]
The point would be for tracking errors in production.

**Comment by sanex3339** [comment]
As i sayd before, with source maps anyone can see all obfuscated code as source code.

**Comment by nickdima** [comment]
Yes, but the source maps don't need to be public. With tools such as [Sentry](https://getsentry.com) you can have private source maps. The way it works is that you upload your source maps to Sentry and the logged exceptions are mapped to the original code instead of the obfuscated one.

**Comment by sanex3339** [comment]
I will try to do that, but can not guarantee

**Comment by nickdima** [comment]
Thanks!

**Comment by sanex3339** [comment]
Do it. Will be ready with 0.7.0

**Comment by nickdima** [comment]
Wow! Awesome!

**Comment by sanex3339** [comment]
Base realisation in master branch, but 0.7.0 will be ready only when i write tests for all node obfuscators.
Look at readme update for new method `obfuscateWithSourceMaps` and CLI usage
