### ISSUE TITLE
NPM Module broken?

### ISSUE THREAD

**Issue by QuantumRevenger** [sanex3339/javascript-obfuscator#8]
After countless attempts to install on Ubuntu 16.04 LTS via NPM, when I run the CLI command javascript-obfuscator it says command not found. Other commands work fine, such as jsuglify.

Any suggestions?

**Comment by QuantumRevenger** [comment]
Turns out your documentation has a mistake, the CLI commands for this module need to be run as sudo npm javascript-obfuscator (otherwise command is not found)

Maybe this should be noted, if someone is having a problem.

**Comment by QuantumRevenger** [comment]
Nope, still broken.

Just ran another module via CLI without a single issue, definitely this that is broken.

**Comment by QuantumRevenger** [comment]
I have traced the problem to a dependency error.

"structure your package.json such that any top-level modules that are also dependencies of other modules are listed lower down." - http://stackoverflow.com/a/20765400

└─┬ javascript-obfuscator@0.6.1
  ├── UNMET PEER DEPENDENCY babel-core@^6.0.0
  └── UNMET PEER DEPENDENCY webpack@1 || ^2.1.0-beta

I tried manually installing the modules and then re-installing javascript-obfuscator but it never works, I will have a look at the package.json and might make a pull request.

**Comment by sanex3339** [comment]
readme for master branch is for 0.7.0 version which is under development

**Comment by sanex3339** [comment]
i update npm package to 0.6.2 version

**Comment by QuantumRevenger** [comment]
Thanks for the update, will keep updated on the development of this project. Also, as of 0.6.2 all the dependency issues are resolved. Just waiting on CLI in 0.7.0 as it's a part of my servers build process (was planned) will temporarily skip the command for now.

**Comment by sanex3339** [comment]
if you use webpack, you can use plugin for it
https://github.com/sanex3339/webpack-obfuscator

**Comment by QuantumRevenger** [comment]
Thank you, unfortunately, I don't use web pack to build .js files as my deployment setup uses proprietary code and special loaders. Unless there is a way to use a CLI command to say perform the following?

obfuscate input.js output.js --parameter --parameter

**Comment by sanex3339** [comment]
before 0.7.0 there no way

**Comment by QuantumRevenger** [comment]
Okay, I'll have to just wait a little longer for the update. Do you have any idea roughly when it might be ready? 

(not an eta, just a guideline; very soon - less than a week, soon - next two weeks, near future - within a month, or distant future - over a month)

**Comment by sanex3339** [comment]
i need to wait while https://github.com/pleerock/class-validator package will update to stable version, because right now it throws error during installation

**Comment by sanex3339** [comment]
Dev version right now was published.
You can install it by following command: 
```
npm install javascript-obfuscator@0.7.0-dev.1 --save
```

**Comment by QuantumRevenger** [comment]
This is great news, thank you for the update. I will deploy this on my build server on Monday.

**Comment by lbayeva** [comment]
I seem to be having the same issue now. Trying to run a client, but get 'command not found'. Was this issue fixed?

**Comment by sanex3339** [comment]
Try `npm link`

**Comment by lbayeva** [comment]
Hmm, that didn't do it, but I can run it like so ./node_modules/.bin/javascript-obfuscator. 
However, I get an error when I give it a .js file:  ..node_modules/esprima/dist/esprima.js:3396
	        var error = new Error(msg);
                     ^
Error: Line 29: Unexpected token
I guess that's outside the scope of this thread though.

**Comment by sanex3339** [comment]
`Error: Line 29: Unexpected token` validate your JS code.

**Comment by lbayeva** [comment]
Oooh, yes, so I'm trying to run this over React files. I guess that won't fly?

**Comment by lbayeva** [comment]
It's not liking things like: "import React from 'react';" "export default Constants;"

**Comment by sanex3339** [comment]
It should support it
http://esprima.org/demo/parse.html

**Comment by sanex3339** [comment]
JSX wont supported by `javascript-obfuscator`. Run obfuscator over bundle.

**Comment by lbayeva** [comment]
Yeah, it's not liking JSX, will try running it over bundle. Thanks!

**Comment by haitham7** [comment]
hello @sanex3339, I have the same issue why?
when I tried to type this 
$ javascript-obfuscator card-edit.js --compact true --self-defending false

return to me 
bash: javascript-obfuscator: command not found
