### ISSUE TITLE
Undefined objects

### ISSUE THREAD

**Issue by nickdima** [sanex3339/javascript-obfuscator#9]
I tried the obfuscator on a couple of complex projects but the obfuscated code has runtime errors that prevents it from running, like some object being undefined.
Any suggestions?

**Comment by sanex3339** [comment]
0.6.0+? I must see problematic source code. I tested obfuscator on angular 2 but it anyway contains errors.

**Comment by sanex3339** [comment]
If you uglify your source code everything will ok?

**Comment by nickdima** [comment]
Latest version from NPM (v 0.7.0-dev.1) and yes, with uglify-js it works

**Comment by sanex3339** [comment]
I should see part of problematic source code

**Comment by nickdima** [comment]
OK, so the error is `Cannot read property '_isFollowing' of undefined` and it's from the Bluebird.js codebase. Look for line 2709 in the attached file.
[bluebird.js.zip](https://github.com/sanex3339/javascript-obfuscator/files/397671/bluebird.js.zip)

**Comment by nickdima** [comment]
So these is the function were it breaks:
```js
Promise.prototype._target = function() {
    var ret = this;
    while (ret._isFollowing()) ret = ret._followee();
    return ret;
};
```
Setting a breakpoint both  in the original code and the obfuscated one I can see that the value of `ret._isFollowing()` is `false` in the plain code and `true` in the obfuscated one, that beeing the source of the problem.

**Comment by sanex3339** [comment]
how i can test this part of code with use of `Bluebird`?

**Comment by sanex3339** [comment]
it looks like i found error.

**Comment by nickdima** [comment]
I tried switching off a few options (compact, rotateUnicodeArray, selfDefending, unicodeArray) but the problem is still there. Looking clo

This is the `_isFollowing` function that returns `true` in the obfuscated code:

```js
Promise.prototype._isFollowing = function () {
    return (this._bitField & 536870912) === 536870912;
};
```
which becomes this

```js
_0xc4b8ce['\x70\x72\x6f\x74\x6f\x74\x79\x70\x65']['\x5f\x69\x73\x46\x6f\x6c\x6c\x6f\x77\x69\x6e\x67'] = function () {
  return (this['\x5f\x62\x69\x74\x46\x69\x65\x6c\x64'] & 0x0) === 0x0;
};
```

**Comment by sanex3339** [comment]
incorrect Utils.decToHex method

**Comment by sanex3339** [comment]
look at `javascript-obfuscator@0.7.0-dev.2`

**Comment by nickdima** [comment]
Thanks for your help! I updated and indeed it's fixed but there's another exception now. I'll investigate it tomorrow. This is the obfuscated code:
`this['\x5f\x6f\x70\x61\x64'] = opad`
and the error is: `opad is not defined`

**Comment by sanex3339** [comment]
I it is this code?
```js
var createHash = require('./create-hash')

var blocksize = 64
var zeroBuffer = new Buffer(blocksize); zeroBuffer.fill(0)

module.exports = Hmac

function Hmac (alg, key) {
  if(!(this instanceof Hmac)) return new Hmac(alg, key)
  this._opad = opad
  this._alg = alg

  key = this._key = !Buffer.isBuffer(key) ? new Buffer(key) : key

  if(key.length > blocksize) {
    key = createHash(alg).update(key).digest()
  } else if(key.length < blocksize) {
    key = Buffer.concat([key, zeroBuffer], blocksize)
  }

  var ipad = this._ipad = new Buffer(blocksize)
  var opad = this._opad = new Buffer(blocksize)

  for(var i = 0; i < blocksize; i++) {
    ipad[i] = key[i] ^ 0x36
    opad[i] = key[i] ^ 0x5C
  }

  this._hash = createHash(alg).update(ipad)
}

Hmac.prototype.update = function (data, enc) {
  this._hash.update(data, enc)
  return this
}

Hmac.prototype.digest = function (enc) {
  var h = this._hash.digest()
  return createHash(this._alg).update(this._opad).update(h).digest(enc)
}
```

it looks like variable `opad` is used before being assigned.
Right now obfuscator will obfuscate variables only after its declaration (+ few additional exclusions https://github.com/sanex3339/javascript-obfuscator/blob/master/test/functional-tests/node-obfuscators/VariableDeclarationObfuscator.spec.ts). 

I should analyze situations like this.

**Comment by nickdima** [comment]
Yes, that's the code!

**Comment by sanex3339** [comment]
`crypto-browserify` is uses old version of `createHmac@1.1.0`. In later versions this code has been  refactored to the correct state
https://github.com/crypto-browserify/createHmac/commit/af30f82e31f55a8288d0a234e39a2d45f271caca

**Comment by sanex3339** [comment]
And i still don't know how to safe detect this situations. 
In the line 
```js
this._opad = opad
```
`opad` can be a global variable, can be a function parameter which will be obfuscated later (in situations, when `VariableDeclarationObfuscator` is called before `FunctionObfuscator`.
```js
function (test) {
    this._test = test;

    //...
    
    var test = '1';
}

function (_0x123456) {
    this.test = _0x123456;

    //...
    
    var _0x789012 = '1';
}
```

**Comment by sanex3339** [comment]
right now you can add `opad` to the `reservedVariables` list

**Comment by nickdima** [comment]
OK, thanks a lot for your help! Really good advices!
